# bs4_minimal_mst : Minimalistic bs4_dash configuration.
# Adjust as per your needs
# Notes :
#     1) this yml maps to template here https://github.com/shambhu112/shinyspring/blob/main/inst/bs4/bs4_minimal.mst
#     2) For advanced users you cna modify template above use it to create your shiny app

 default:
## DO NOT Change the following
  dashboard_template: bs4_dash
  template_file: !expr system.file("bs4/bs4_minimal.mst" , package = "shinyspring")  # Note: Advanced users can define new template
  dummy_test.mod_name: dummy_mod
  dummy_test.weird_param: dummy


# Adjust as per your App but defaults work well.
  sweetmod_config : config.yml
  code_gen_location: '.'
  preload_dataset: true
  builtin_datasets: iris ; mtcars
  source_file_onstartup: on_startup.R

# datsets : This is the approach to pre-load datasets
  ds.iris.type: built_in
  ds.iris.connection: iris

  ds.mtcars.type: built_in
  ds.mtcars.connection: mtcars

  ds.air_quality.type: built_in
  ds.air_quality.connection: airquality


# Note you can preload files and targets also by adjusting the following commeted items

# Dashboard UI information : You should customize
  app_title: Corelation Mod
  footer_left: Built on Shiny Spring
  footer_right: version 1.0  #app_name
  sidebar_expand_onhover: FALSE
  dark_theme: FALSE
  header_href: https://www.shinyspring.dev
  header_image: https://storage.googleapis.com/shiny-pics/spring_logo.png
  header_fixed: 'TRUE'
  title_color: primary
  app_title_h3: Corelation Analysis
  side_bar_fixed: TRUE
  side_bar_header: Sample App
  header_opacity: 0.8

# Authentication : Use Shinymanager based auth or not
  basic_auth: FALSE

# Menus : You should customize - documentation here $TODO link
# Note: the ui_function and server_function are from sweetmods or your custom modules
  menus: [
    { title: Corelation Analysis , name: corr_tab , icon: indent , comma: true },
    { title: Data Exploration , name: explore_tab , icon: chart-bar , comma: true },
    { title: Credits , name: credits_tab , icon: heart , comma: false }
  ]


# Sweetmods configurations : : You should customize - documentation here $TODO
  corr_tab.mod_name: corr_dup_mod
  corr_tab.ui_function: corr_mod_ui
  corr_tab.server_function: corr_mod_server
  corr_tab.onload_function: corr_mod_onLoad
  corr_tab.max_rows: 10000

  explore_tab.mod_name: esquisse_mod

  credits_tab.mod_name: dummy_mod

 dev:
  code_gen_location: dev/play

