# bs4_minimal_mst : Minimalistic bs4_dash configuration.
# Adjust as per your needs
# Notes :
#     1) this yml maps to template here https://github.com/shambhu112/shinyspring/blob/main/inst/bs4/bs4_minimal.mst
#     2) For advanced users you cna modify template above use it to create your shiny app

default:
## DO NOT Change the following
  dashboard_template: bs4_dash
  template_file: !expr system.file("bs4/bs4_minimal.mst" , package = "shinyspring")  # Note: Advanced users can define new template

## Adjust as per your App but defaults work well.
  sweetmod_config : config.yml
  code_gen_location: '.'

# Dashboard UI information : You should customize
  app_title: ShinySpring
  footer_left: Built on Shiny Spring
  footer_right: version 1.0  #app_name
  sidebar_expand_onhover: FALSE
  dark_theme: FALSE
  header_href: https://www.shinyspring.dev
  header_image: https://storage.googleapis.com/shiny-pics/spring_logo.png
  header_fixed: 'TRUE'
  title_color: primary
  app_title_h3: Esquiee Mod Sample
  side_bar_fixed: TRUE
  side_bar_header: Data Exploration

# Menus : You should customize - documentation here $TODO link for Menus
# Note: the ui_function and server_function are from sweetmods or your custom modules
  menus: [
    { title: Data Exploration , name: esquiee_mod , icon: chart-bar , comma: true ,
      ui_function: esquisse_wrapper_ui , server_function: esquisse_wrapper_server},
    { title: Credits , name: credits_mod , icon: heart , comma: false ,
      ui_function: demo_ui , server_function: demo_server}
  ]

# Sweetmods configurations
  preload_dataset: TRUE
#  file_preloads : ../tests/testthat/CHART4_NM.csv ; ../tests/testthat/CHART2_MO_COUNTIES.csv ; ..tests/testthat/DC_sis_dist.feather
#  file_preloads_ds_name : new_mexico ; missiori ; sister_branches
# tar_loads : Note: tar_loads from targets package are supported
  builtin_datasets : iris ; mtcars

#Sweetmod params
  bank_mod.prop1: This is Prop 1 for Bank modules
  branch_mod.prop1: This is Prop 1for Branch Mo
  branch_mod.prop2: This is Prop 2 for branch Mod


dev:
  code_gen_location: dev/play

